DROP DATABASE IF EXISTS work_order_system;
CREATE DATABASE work_order_system;
USE work_order_system;
-- ==========================
-- TABLA CUSTOMER
-- ==========================
CREATE TABLE CUSTOMER (
ID_CUSTOMER INT AUTO_INCREMENT PRIMARY KEY,
FIRST_NAME VARCHAR(100) NOT NULL,
LAST_NAME VARCHAR(100) NOT NULL,
EMAIL VARCHAR(150),
PHONE VARCHAR(30),
STATUS VARCHAR(30) DEFAULT 'ACTIVE'
);
-- ==========================
-- TABLA ADDRESS
-- ==========================
CREATE TABLE ADDRESS (
ID_ADDRESS INT AUTO_INCREMENT PRIMARY KEY,
ID_CUSTOMER INT NOT NULL,
STREET VARCHAR(200),
CITY VARCHAR(100),
REGION VARCHAR(100),
FOREIGN KEY (ID_CUSTOMER)
REFERENCES CUSTOMER(ID_CUSTOMER)
);
-- ==========================
-- TABLA PROVISION
-- ==========================
CREATE TABLE PROVISION (
ID_PROVISION INT AUTO_INCREMENT PRIMARY KEY,
PROVISION_NAME VARCHAR(100) NOT NULL,
DESCRIPTION VARCHAR(250)
);
-- ==========================
-- TABLA SERVICE
-- ==========================
CREATE TABLE SERVICE (
ID_SERVICE INT AUTO_INCREMENT PRIMARY KEY,
SERVICE_NAME VARCHAR(100) NOT NULL,
MONTHLY_COST DECIMAL(10,2),
STATUS VARCHAR(20) DEFAULT 'ACTIVE'
);
-- ==========================
-- TABLA SERVICE_PROVISION
-- ==========================
CREATE TABLE SERVICE_PROVISION (
ID_SERVICE INT,
ID_PROVISION INT,
PRIMARY KEY(ID_SERVICE, ID_PROVISION),
FOREIGN KEY(ID_SERVICE)
    REFERENCES SERVICE(ID_SERVICE),

FOREIGN KEY(ID_PROVISION)
    REFERENCES PROVISION(ID_PROVISION)

);
-- ==========================
-- TABLA EQUIPMENT
-- ==========================
CREATE TABLE EQUIPMENT (
ID_EQUIPMENT INT AUTO_INCREMENT PRIMARY KEY,
EQUIPMENT_NAME VARCHAR(100),
BRAND VARCHAR(100),
MODEL VARCHAR(100),
STATUS VARCHAR(20) DEFAULT 'ACTIVE'
);
-- ==========================
-- TABLA EQUIPMENT_PROVISION
-- ==========================
CREATE TABLE EQUIPMENT_PROVISION (
ID_EQUIPMENT INT,
ID_PROVISION INT,
PRIMARY KEY(ID_EQUIPMENT, ID_PROVISION),

FOREIGN KEY(ID_EQUIPMENT)
    REFERENCES EQUIPMENT(ID_EQUIPMENT),

FOREIGN KEY(ID_PROVISION)
    REFERENCES PROVISION(ID_PROVISION)

);
-- ==========================
-- TABLA OFFER
-- ==========================
CREATE TABLE OFFER (
ID_OFFER INT AUTO_INCREMENT PRIMARY KEY,
OFFER_NAME VARCHAR(150),
OFFER_PRICE DECIMAL(10,2),
CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
-- ==========================
-- TABLA OFFER_SERVICE
-- ==========================
CREATE TABLE OFFER_SERVICE (
ID_OFFER INT,
ID_SERVICE INT,
PRIMARY KEY(ID_OFFER, ID_SERVICE),

FOREIGN KEY(ID_OFFER)
    REFERENCES OFFER(ID_OFFER),

FOREIGN KEY(ID_SERVICE)
    REFERENCES SERVICE(ID_SERVICE)

);
-- ==========================
-- TABLA OFFER_EQUIPMENT
-- ==========================
CREATE TABLE OFFER_EQUIPMENT (
ID_OFFER INT,
ID_EQUIPMENT INT,
PRIMARY KEY(ID_OFFER, ID_EQUIPMENT),

FOREIGN KEY(ID_OFFER)
    REFERENCES OFFER(ID_OFFER),

FOREIGN KEY(ID_EQUIPMENT)
    REFERENCES EQUIPMENT(ID_EQUIPMENT)

);
-- ==========================
-- TABLA OFFER_PROVISION
-- ==========================
CREATE TABLE OFFER_PROVISION (
ID_OFFER INT,
ID_PROVISION INT,
PRIMARY KEY(ID_OFFER, ID_PROVISION),

FOREIGN KEY(ID_OFFER)
    REFERENCES OFFER(ID_OFFER),

FOREIGN KEY(ID_PROVISION)
    REFERENCES PROVISION(ID_PROVISION)

);
-- ==========================
-- CUSTOMER_SERVICE
-- ==========================
CREATE TABLE CUSTOMER_SERVICE (
ID_CUSTOMER INT,
ID_SERVICE INT,
PRIMARY KEY(ID_CUSTOMER, ID_SERVICE),

FOREIGN KEY(ID_CUSTOMER)
    REFERENCES CUSTOMER(ID_CUSTOMER),

FOREIGN KEY(ID_SERVICE)
    REFERENCES SERVICE(ID_SERVICE)

);
-- ==========================
-- CUSTOMER_EQUIPMENT
-- ==========================
CREATE TABLE CUSTOMER_EQUIPMENT (
ID_CUSTOMER INT,
ID_EQUIPMENT INT,
PRIMARY KEY(ID_CUSTOMER, ID_EQUIPMENT),

FOREIGN KEY(ID_CUSTOMER)
    REFERENCES CUSTOMER(ID_CUSTOMER),

FOREIGN KEY(ID_EQUIPMENT)
    REFERENCES EQUIPMENT(ID_EQUIPMENT)

);
-- ==========================
-- DATOS MAESTROS
-- ==========================
INSERT INTO PROVISION
(PROVISION_NAME, DESCRIPTION)
VALUES
('Internet','Servicio Internet'),
('Telefonia','Servicio Telefonico'),
('Television','Servicio TV'),
('Streaming','Servicio Streaming');
INSERT INTO CUSTOMER
(FIRST_NAME,LAST_NAME,EMAIL,PHONE)
VALUES
('Benjamin','Silva','benjamin@test.cl','987654321'),
('Juan','Perez','juan@test.cl','912345678'),
('Maria','Gonzalez','maria@test.cl','923456789');
INSERT INTO ADDRESS
(ID_CUSTOMER,STREET,CITY,REGION)
VALUES
(1,'Av. Central 100','Maipu','RM'),
(2,'Los Heroes 220','Santiago','RM'),
(3,'Las Flores 99','Puente Alto','RM');